Redesign user views
kir-dev/konyha pull request #66
Opened 2020-11-14 02:15 UTC by triszt4n

Closes #40 

### What's new:
* User view designs. :art: 
* Some fixes, see comments below. :bug:

2020-11-14 02:18 UTC, triszt4n commented
Issue #60 could be solved with a new link on the user show page. (under the email address maybe)
But that issue needs advanced pék knowledge, I think.

2020-11-14 02:20 UTC, triszt4n commented
This PR might even solve issue #55 but not on appliance show page (that wouldn't be smart), but on the kitchen show page AND on the user show page.

2020-11-14 02:24 UTC, triszt4n commented on app/controllers/appliance_comments_controller.rb
>    end
It seems, if the appliance didn't have any comments, the last method would give back `nil`, with which `updated_at` in `sort_by` would always break the page from loading.

2020-11-14 02:24 UTC, triszt4n commented on app/controllers/appliance_comments_controller.rb
>    end
The filter_map is a clever solution for getting only the existing comments.

2020-11-14 02:25 UTC, triszt4n commented on app/controllers/appliances_controller.rb
> +    @appliance = Appliance.new(params.permit(:kitchen_id))
Making it possible to auto-fill in advance the kitchen field when creating new appliance.

2020-11-14 02:26 UTC, triszt4n commented on app/controllers/application_controller.rb
> +
Might be useful for later in view logics. (I've used it) If there's cleverer solution, let me know! :pray:

2020-11-14 02:27 UTC, triszt4n commented on app/views/appliances/show.html.haml
> +            = link_to comment.owner.name, user_path(comment.owner), class: "hover:underline"
Yeah, this was a little mistyping accident that I corrected.

2020-11-14 10:46 UTC, SepsiLaszlo requested changes
Excellent work!
The views are very good to look at and they are perfectly ergonomic!

I left some suggestions on how we can better determine if some UI elements needs to be rendered or not.

2020-11-14 10:46 UTC, SepsiLaszlo commented on app/controllers/appliance_comments_controller.rb
>    end
Great solution! 
In this case I think the `filter_map` is the clearest implementation.
There is another way to remove `nil ` values from an array which could be useful in other cases. We could use the  [compact](https://ruby-doc.com/core/Array.html#method-i-compact) method to remove all `nil` values.

2020-11-14 10:46 UTC, SepsiLaszlo commented on app/controllers/application_controller.rb
> +
This is an interesting problem.
We could check permissions in views based on roles with helper methods like you did which is very clear to read.
Or we use the polices for the corresponding action. This is not elegant, but it decouples the view from the authorization. (If some view's permission is changed we only have to change it in the policy not in all views.)
I will make a suggestion in the appropriate view.

2020-11-14 10:46 UTC, SepsiLaszlo commented on app/views/layouts/_nav.html.haml
> +      - if am_i_admin?
We could check if the action of the link is permitted for the `current_user` and render the button based on that.
Currently we could something like this:
```suggestion
      - if UserPolicy.new(current_user, current_user).index?
```
But if we create a constructor for the `UserPolicy` with one argument we could use something like this:
```suggestion
      - if UserPolicy.new(current_user).index?
```
The constructor must accept both one and two arguments. One way to achive this is with a default argument.
The mentioned constructor in the `UserPolicy` for this to work:
```ruby
  def initialize(user, record = nil)
    super
  end
```

2020-11-14 10:46 UTC, SepsiLaszlo commented on app/views/users/index.html.haml
> +          - if user.admin
I think this is fine, we can keep it that way. No need to use policy here.

2020-11-14 10:46 UTC, SepsiLaszlo commented on app/views/users/show.html.haml
> +  - if @user.admin
We can keep that too.

2020-11-14 10:46 UTC, SepsiLaszlo commented on app/views/users/show.html.haml
> +- if current_user == @user or am_i_admin?
We could use a policy here too.
```suggestion
- if UserPolicy.new(current_user).update?
```

2020-11-15 21:04 UTC, SepsiLaszlo commented
There is a more compact way for using policies in views. I updated the suggestions.

2020-11-22 10:21 UTC, SepsiLaszlo approved these changes

2020-11-22 10:22 UTC, merged